---
classes                           :
                                    - ceph::repo
                                    - ceph::deploy
                                    - ceph::user
                                    - ceph::common
